name: "pi gen test"
on: [push]
jobs:
  pi-gen-upload-image:
    runs-on: ubuntu-latest
    steps:
      - uses: usimd/pi-gen-action@v1
        id: build
        with:
          compression: xz
          compression-level: 9
          disable-first-boot-user-rename: true
          export-last-stage-only: true
          hostname: test-hostname
          image-name: test
          keyboard-keymap: us
          keyboard-layout: English (US)
          locale: en_US.UTF-8
          password: password
          pi-gen-version: arm64
          release: bullseye
          timezone: America/Chicago
          username: test-user
          wpa-country: US

      - uses: actions/upload-artifact@v3
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}
